import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-background">
      <Navbar />
      <main className="flex-grow max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24 w-full">
        <div className="space-y-8 text-secondary leading-relaxed">
          <div>
            <h1 className="font-serif text-3xl md:text-4xl text-foreground mb-4">Privacy Policy</h1>
            <p className="text-sm">Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
          </div>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">1. Introduction</h2>
            <p>
              PassNotice (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) provides workflow automation software for advocates and legal professionals. This Privacy Policy explains how we collect, use, and protect your information when you use our software and services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">2. Information We Collect</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account Information:</strong> We collect your name, email address, and authentication credentials when you register.</li>
              <li><strong>Client Data:</strong> Information you upload or enter regarding your clients or debtors (such as names, amounts, and contact details) is securely stored to generate your requested legal notices.</li>
              <li><strong>Templates and Notices:</strong> We store the legal notice templates you upload and the documents generated by the system.</li>
              <li><strong>Technical Logs:</strong> We collect standard technical information (like IP addresses and error logs) strictly for debugging and maintaining service reliability.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">3. Google API Services Usage (Gmail Integration)</h2>
            <p>
              Our application allows you to voluntarily connect your Google Gmail account via OAuth to send legal notices directly from your own email address. Our use of information received from Google APIs adheres to the <a href="https://developers.google.com/terms/api-services-user-data-policy" className="text-accent hover:underline" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Requested Scopes:</strong> We strictly request only the permission to send emails on your behalf (<code>https://www.googleapis.com/auth/gmail.send</code>) and basic identity information to verify your account.</li>
              <li><strong>No Mailbox Access:</strong> We do <strong>not</strong> request permissions to read, modify, delete, or otherwise access your existing emails or mailbox contents.</li>
              <li><strong>Secure Token Storage:</strong> If you authorize the connection, your OAuth access and refresh tokens are securely encrypted at rest in our database. They are solely used to maintain your authorized connection and execute the sending of your legal notices.</li>
              <li><strong>Revocation:</strong> You can disconnect your Gmail account and revoke these tokens at any time from your settings page.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">4. Data Sharing and Third Parties</h2>
            <p>
              We do not sell, rent, or trade your personal information or your client data to third parties. Data is shared only with strictly necessary infrastructure providers (such as secure cloud hosting environments) required to operate the service. We do not use third-party email service providers to send your legal notices; emails are sent exclusively through your directly connected Gmail account using the official Google API.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">5. Security</h2>
            <p>
              We employ industry-standard, reasonable security practices to protect your data, including encryption at rest for sensitive credentials (like OAuth tokens) and in transit (via HTTPS). While we strive to protect your information, no system can guarantee 100% absolute security against all unauthorized access.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">6. Data Retention and Deletion</h2>
            <p>
              We retain your data for as long as your account is active or as needed to provide you services. You may request the deletion of your account and associated client data at any time by contacting our support team. Upon request, we will promptly delete your data from our active databases, subject to any legal obligations.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-serif text-xl text-foreground">7. Contact Us</h2>
            <p>
              If you have any questions or concerns regarding this Privacy Policy or our data practices, please contact us at: <a href="mailto:hello@passnotice.com" className="text-accent hover:underline">hello@passnotice.com</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
